"""Added coupons table

Revision ID: 0033
Revises: 0032
Create Date: 2026-04-13 08:02:11.353660+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0033'
down_revision: str | None = '0032'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_coupons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.Text(), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reuse_policy', sa.Text(), server_default='single_use', nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_till', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_checkout_coupons_active_valid_till', 'checkout_coupons', ['is_active', 'valid_till'], unique=False)
    op.create_table('coupon_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['checkout_coupons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_id', 'user_id', name='uq_coupon_users_coupon_user')
    )
    op.create_index(op.f('ix_coupon_users_coupon_id'), 'coupon_users', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_users_user_id'), 'coupon_users', ['user_id'], unique=False)
    op.add_column('payment_events', sa.Column('coupon_code', sa.Text(), nullable=True))
    op.create_index(op.f('ix_payment_events_coupon_code'), 'payment_events', ['coupon_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_coupon_code'), table_name='payment_events')
    op.drop_column('payment_events', 'coupon_code')
    op.drop_index(op.f('ix_coupon_users_user_id'), table_name='coupon_users')
    op.drop_index(op.f('ix_coupon_users_coupon_id'), table_name='coupon_users')
    op.drop_table('coupon_users')
    op.drop_index('ix_checkout_coupons_active_valid_till', table_name='checkout_coupons')
    op.drop_table('checkout_coupons')
    # ### end Alembic commands ###
